### ISSUE TITLE
Server 的網頁部份

### ISSUE THREAD

**Issue by pakls** [g0v/newshelper-extension#26]
因為想要幫忙提倡使用新聞小幫手, 所以有時會把已回報的新聞轉貼, 試了一段時間發現應該有可以更完善的一些小地方
1. 例, http://newshelper.g0v.tw/#reported 的 table 裡, 可以把 link 由 http://newshelper.g0v.tw/index/log/761#logs 改為 http://newshelper.g0v.tw/index/log/761
   轉貼給別人看的時候, 一點出來就會是更新後的說明, 而不是歷史
2. 在 http://newshelper.g0v.tw/index/log/761 中也加上像首頁一樣的 "下載瀏覽器擴充套件，現在就把小幫手帶回家" 鼓勵使用者安裝

**Comment by wildskyf** [comment]
Hi @pakls 
因為這個 repo 是 for 擴充套件，所以幫你把 issue 移動到 [g0v/newshelper-backend](https://github.com/g0v/newshelper-backend) 這個 repo 下 :)
