### ISSUE TITLE
Firefox的擴充元件是否已不能使用？

### ISSUE THREAD

**Issue by J4X0N** [g0v/newshelper-extension#48]
突然發現我裝了很久，結果都沒跑出警示出來，請問是不是已經不能使用了呢？

**Comment by kcwu** [comment]
試試[新聞小幫手測試專用頁](https://www.facebook.com/%E6%96%B0%E8%81%9E%E5%B0%8F%E5%B9%AB%E6%89%8B%E6%B8%AC%E8%A9%A6%E5%B0%88%E7%94%A8-494676360619618/)有沒有跑出警示

**Comment by ronnywang** [comment]
Firefox 問題可以至 https://github.com/racklin/newshelper-firefox 詢問

**Comment by J4X0N** [comment]
去那邊看似乎33版以後就沒效了QQ
作者好像也沒維護
謝謝

**Comment by racklin** [comment]
@J4X0N @ronnywang Firefox 38 後 addons-sdk 由 cfx -> jpm 且有部份不相容，近年的確都用 chrome , 近日會研究，昇級小幫手版本。
造成不便，請見諒。

**Comment by racklin** [comment]
@J4X0N @ronnywang  目前 1.6.1 版本已釋出，已和最新 chrome 版本程式同步。
等待 mozilla review，便會自動更新，或您可以立即自行下載更新。

https://addons.mozilla.org/en-US/firefox/addon/newshelper-firefox/versions/?page=1#version-1.6.1。

**Comment by ronnywang** [comment]
謝謝 @racklin  !

**Comment by J4X0N** [comment]
感謝@racklin大大！！！
